# Configure this Discovery Server
eureka:
  instance:
    hostname: ${CONTAINER_IP:@container.ip@}
    #enableSelfPreservation: false
    preferIpAddress: true
    # DO NOT DO THIS IN PRODUCTION
    leaseRenewalIntervalInSeconds: 5

  client:
    registerWithEureka: false
    fetchRegistry: false


server:
  port: ${SERVICE_PORT:@service.port@}

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

